title: Yogicat | Frontend developer (also designer) from Seoul
email: hi@yogicat.dev
description: Yogicat is a frontend developer and multi disciplinary designer from Seoul.
baseurl: "/"
url: "https://yogicat.dev"
github_usename: yogicat
google_analytics: UA-138178661-1

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

highlighter: rouge

permalink: /:year/:month/:title.html


jekyll_compose:
  draft_default_front_matter:
    title:
    categories: blog
    tags: [programming, xyz, til, algorithm]
  post_default_front_matter:
    title:
    categories: blog
    tags: [programming, xyz, til, algorithm]

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

img_url: "https://yogicat-blog.s3.ap-northeast-2.amazonaws.com/cover/"