title: Dahe Oh | Frontend developer (also designer) from Seoul
email: dahe.oh@gmail.com
description: Dahe Oh is a frontend developer and multi disciplinary designer from Seoul.
baseurl: "/"
url: "https://yogicat.dev"
github_usename: yogicat
google_analytics: UA-127168148-1

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

highlighter: rouge

permalink: /:year/:month/:title.html
# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  permalink: '/page/:num/'
  title: title
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 5
    after: 5

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
