title: Dahe Oh | Frontend developer (also designer) from Seoul
email: dahe.oh@gmail.com
description: Dahe Oh is a frontend developer and multi disciplinary designer from Seoul.
baseurl: "/"
url: "https://yogicat.dev"
github_usename: yogicat
google_analytics: UA-127168148-1

# Build settings
markdown: kramdown
highlighter: rouge


theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "book"
    values:
      layout: "book"
  -
    scope:
      path: ""
    values:
      layout: "default"


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
